### ISSUE TITLE
Please correct the function close

### ISSUE THREAD

**Issue by SmakPHP** [RapidSpike/php-browsermob-proxy#1]
https://github.com/lightbody/browsermob-proxy
Shuts down the proxy and closes the port. [port] in request path it is port where your proxy was started | DELETE | /proxy/[port]
-- | -- | --

return \Requests::delete("http://{$this->browsermob_url}/proxy/{$this->port}");

**Comment by yippeykeiyay** [comment]
Fixed by #2
